"""Add admin features and scraping stats

Revision ID: 11ff22fc4c2d
Revises: 51c4d79c5a02
Create Date: 2025-11-19 15:18:01.158864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11ff22fc4c2d'
down_revision: Union[str, None] = '51c4d79c5a02'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_scraping_stats_created_at', table_name='scraping_stats')
    op.drop_index('ix_scraping_stats_id', table_name='scraping_stats')
    op.drop_index('ix_scraping_stats_site_name', table_name='scraping_stats')
    op.drop_table('scraping_stats')
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.create_table('scraping_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('site_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('response_time', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='scraping_stats_pkey')
    )
    op.create_index('ix_scraping_stats_site_name', 'scraping_stats', ['site_name'], unique=False)
    op.create_index('ix_scraping_stats_id', 'scraping_stats', ['id'], unique=False)
    op.create_index('ix_scraping_stats_created_at', 'scraping_stats', ['created_at'], unique=False)
    # ### end Alembic commands ###
