"""add user preferences table for notifications

Revision ID: 33b2bd57bf5e
Revises: b5ac16a84072
Create Date: 2025-11-17 14:08:19.257948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33b2bd57bf5e'
down_revision: Union[str, None] = 'b5ac16a84072'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
