"""Add check_frequency field to Product model

Revision ID: 51c4d79c5a02
Revises: 33b2bd57bf5e
Create Date: 2025-11-18 14:37:01.916234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51c4d79c5a02'
down_revision: Union[str, None] = '33b2bd57bf5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with default value to avoid NOT NULL constraint violation on existing rows
    op.add_column('products', sa.Column('check_frequency', sa.Integer(), nullable=False, server_default='24'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'check_frequency')
    # ### end Alembic commands ###
