"""Add availability tracking fields to product

Revision ID: b5ac16a84072
Revises: ca6901d62d80
Create Date: 2025-11-14 15:03:30.013579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5ac16a84072'
down_revision: Union[str, None] = 'ca6901d62d80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('is_available', sa.Boolean(), nullable=False))
    op.add_column('products', sa.Column('unavailable_since', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'unavailable_since')
    op.drop_column('products', 'is_available')
    # ### end Alembic commands ###
