"""Add price_history table for tracking price changes over time

Revision ID: ca6901d62d80
Revises: 840e1a6bf3cc
Create Date: 2025-11-10 21:03:16.492259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca6901d62d80'
down_revision: Union[str, None] = '840e1a6bf3cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
